
#The Seventh House: The House of Relationships.

def theSeventhHouse():
  zodiac = {"Aries": ["Libra","With the seventh house set in the sign of Aries, tact is not seen very often in close relationships. There is always something hidden in the culture of conflict that needs to be learned, and the most typical scenario speaks of one’s tendency to dismiss the benefits of conflict, avoiding it even though it would be constructive and useful. This will represent a challenge in creating clear boundaries and in any case of repression, it will speak of anger and aggression linked to intimate bonds. In a very positive setting, this is a position that points to resourcefulness and vigor of a partner, and a strong attraction filled with rich sexual experiences in marriage and serious relationships that a person has. As soon as constructive conflict is accepted and strong boundaries set towards those who endanger one’s wellbeing, this becomes an energizing seventh house that gives strength and makes us feel alive."],
            "Cancer": ["Capricorn","Even though the seventh house in Capricorn often speaks of restrictions and characters that are hard to combine with one’s core personality, it gives a certain sense of responsibility and patience towards other people. With enough rest and solitude, this is someone who can predict other people’s behavior and approach them in a way that makes everyone feel protected and safe. The main challenge here is in breaking all walls around the heart of the chart’s owner and people in their life. Every hurt will reflect in the inability to form a close relationship, and memories tend to distract a person from building a future they wish for. If there is guilt involved and they think they have made too many mistakes, these individuals could even give up on love, thinking they don’t deserve it or they are unworthy of those who’d make them truly happy. Each lesson learned here has to be deep and complete, while one has to always make progress overcoming the static need to stand in one place, tied to those who don’t make them smile."],
            "Scorpio": ["Taurus","With the seventh house in Taurus, there is always a challenge of two sides of Venus in the field of relationships. Taurus is a sign of practical values and grounded, earthly beauty, sometimes too simple for blue-blooded  individuals turned to fine, sensitive, outer beauty. The seventh house is corresponding to the sign of Libra, and as such speaks of outer beauty, makeup, pose and vanity in its challenges. When these two extremes coincide, envy will easily come to the surface and matters of balance will be emphasized, once again. Relationships can become vain and judgmental, typical for those who weren’t told often enough how pretty they are in all their glory. It is of outmost importance for outer and inner beauty to connect in one whole, so that all relationships in a person’s life can become truly enjoyable and filled with sensual physical contact and intimacy, which are provided by Taurus when matters  of Venus are settled."],
            "Aquarius": ["Leo","With the seventh house in Leo, all relationships depend solely on a person’s ability to find middle ground and a point of agreement with others instead of compromising senselessly and going to extremes of doing and not doing what others want. The main challenge of Leo hides in oneness found in connection with the rest of the human race, and since this already puts an emphasis on an Ascendant in Aquarius, this is always hard to reach as an innovative, strange, and special individual. These people need confident partners who don’t take things too personally, and have to discover ways in which they can function as one with those who are less rational and far fierier than they seem to be. There is no authority in “we” and for as long as they realize that respect has to be unconditional and flowing both ways equally, they will form healthy bonds filled with warmth."],
            "Virgo": ["Pisces","When the seventh house begins in Pisces, matters of trust are of outmost importance for any healthy relationships a person might have. Beliefs will create destiny, while there is often some sort of mission one has to fulfill in order to find satisfaction and happiness. In many cases this is a position that speaks of betrayal and strange partners, intimate bonds with people who are talented and artistic but also unstable, lost, far away, psychologically challenged or turned to substance abuse of some kind. Dependencies are almost inevitable here until one learns about ways to believe in their own abilities and believe in others in the right way and with clearly set boundaries. There is a lot of emotion and romance here and for as long as the minds of these individuals don’t meddle in matters of the heart they will advance towards more and more fulfilling relationships through life. There is magic to this position and the greatest potential for a fairytale ending is hidden here, if only there is enough faith and devotion to reach this destination."],
            "Gemini": ["Sagittarius","If the seventh house is set in Sagittarius, the mutable nature of it interferes with one’s ability to form lasting relationships. There is always something unreachable set in this distant sign, and the inability to materialize desires often leads to long-distance relationships, or simply bonds with people who aren’t stable, close, intimate, or those who are already taken. With Sagittarius, there is always a philosophy that leads to certain events and this position will simply materialize convictions. In the practical sense, we can understand this best through an example of a person who lives convinced that all people of opposite sex are not to be trusted. This specific conviction will lead to relationships that will prove them right, and one will be disappointed again and again, proving the image projected to the outer world in cycles. To move from repetitive choices, the person needs to learn and widen their perspective until they realize what sort of inner change can lead to a more satisfying environment."],
            "Libra": ["Aries","With the seventh house set in the sign of Aries, tact is not seen very often in close relationships. There is always something hidden in the culture of conflict that needs to be learned, and the most typical scenario speaks of one’s tendency to dismiss the benefits of conflict, avoiding it even though it would be constructive and useful. This will represent a challenge in creating clear boundaries and in any case of repression, it will speak of anger and aggression linked to intimate bonds. In a very positive setting, this is a position that points to resourcefulness and vigor of a partner, and a strong attraction filled with rich sexual experiences in marriage and serious relationships that a person has. As soon as constructive conflict is accepted and strong boundaries set towards those who endanger one’s wellbeing, this becomes an energizing seventh house that gives strength and makes us feel alive."],
            "Capricorn": ["Cancer","If the seventh house begins in the sign of Cancer, there is a lot left in the field of relationships from our ancestors and family. It is almost impossible to separate one’s personal goals and bonds formed with other people from those of parents and close family members that presented role models in the person’s upbringing. With this position, ego and personality have to be well defined, and the Sun needs to be nurtured through creative activities and a thorough approach to the child within. All this person needs is awareness of their true core and specifics of personality that set them apart from family members and values learned at home. When partners are chosen in accordance with one’s sensibility and character, relationships will be filled with tenderness, emotion and intimacy, leading to a healthy family life and functional marriages that last."],
            "Taurus": ["Scorpio","With the seventh house set in the sign of Scorpio, ultimate intimacy is needed in order for the person to find satisfaction. This is a position very hard to please and the nature of the first house already shows the ability to create tender intimacy and closeness, usually dismissed and diminished by others. The trick to finding happiness with the position such as this one hides in the Moon’s pool of emotion, love for Self and the ability to forgive, forget, and make changes when the right time for them comes. Once this person sets deserved satisfaction on the top of their priority ladder, things will become easier and ties to other people will fade while a healthy relationship with their own life, decisions, and choices becomes imperative. Until then, jealousy and possessive relationships are inevitable, while happiness becomes this distant light seen from the underground ruled by Scorpio."],
            "Leo": ["Aquarius","Aquarius is a sign that speaks of divorce and separation, as well as all oppositions that are combined in perfect harmony in nature around us. When the system is balanced and a person has an equal perception of their Self and others, this is a liberating sign that will bring a lot of excitement, joy, and constant surprises, while emotions tend to spark every now and then, creating fireworks in their love life. Still, Aquarius comes after Capricorn and its basis is cold and generic, while the mental nature of Aquarius doesn’t help emotional closeness. This is much less a challenge of honesty towards others, but rather a challenge of honesty towards oneself. We need to understand that partners show as unstable simply because of this person’s inner need to reflect in people who are different and on the move. Closeness has to come from the deepest core of the heart, and with a strongly set Moon, this is the seventh house that fills everyone around this person with excitement and beauty."],
            "Pisces": ["Virgo","The seventh house set in the sign of Virgo speaks of humility and brings focus to matters of criticism, the ability to find satisfaction in the real world and form relationships that don’t have to be perfect in order to last. There is always something that needs to be fixed in the sign of Virgo and this position will make a person look for something impossible to reach in many cases, or make them settle for less than they deserve out of feelings of guilt, incompetence or a simple lack of self-worth. All unhealthy issues will tend to accumulate here so this is a house that needs a lot of cleansing, constructive efforts and changes in order to reach the state which satisfies that dreamy first house in Pisces. Matters of faith and disappointments greatly depend on the story of Venus, for one obviously needs to set reasonable expectations through dealing with other people."],
            "Sagittarius": ["Gemini","If the seventh house is set in Gemini, there is obviously a lot to talk about in this lifetime. This is a person who sees communication as a key to any situation at hand. Closeness is reached through conversations, people are met at social gatherings, and the image of a talkative friend is often too accented. This can lead to detachment and one’s inability to create true intimate contact, especially if the Moon is not strong enough to handle the mental capacity of a person. It is always important to work on the emotional state when this is the case, for only deep emotion, forgiveness and childish joy can make this Gemini partner as happy and light as it is supposed to be. In many cases, this is a position that speaks of multiple marriages, often as a consequence of overthinking combined with strange mental spontaneity, while not in sync with one’s heart."]}  
  h= rising_star = input("What is your rising star? :\n" )
  h= rising_star.capitalize()
  if h not in zodiac:
    print("This isn't a rising star. Please write your rising star.")
    theSeventhHouse()
  else:
    print("Your seventh house is " + zodiac[h][0] + ".")
    print(zodiac[h][1])

theSeventhHouse()
